### ISSUE TITLE
API instead of command line.

### ISSUE THREAD

**Issue by trusktr** [eface2face/spacebars-compiler#1]
It seems that this is intended for command-line only. I'd like to require() it in my node module and use it programmatically so that the return value (or callback) gives me access to a template finction, then I could do something like `template(data)` to render it.

**Comment by murillo128** [comment]
Hi trusktr,

Yes, indeed this is command line utility only. You may take a look at this project instead:
https://github.com/eface2face/meteor-client

We also created a jquery plugin for making it easier to use meteor blaze templates here:
https://github.com/eface2face/jquery-meteor-blaze

You can use the generated JS files from the spacebars-compiler there, instead of compiling them on run time.

We have still not got much time to document them in deep, but we hope to do soon. Any feedback would be very welcome.

BR
Sergio
